# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

steps:
- task: CopyFiles@2
  inputs:
    SourceFolder: 'https://github.com/bharatchn/AzureWindowsVM/tree/master/AzureResourceGroup1'
    Contents: '**'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Resource Group'
    azureResourceManagerConnection: 'Azure Training'
    subscriptionId: 'a27dd098-1a6a-4384-977c-53bbf66ef042'
    action: 'Create Or Update Resource Group'
    resourceGroupName: 'RG-CTG-BHARAT-KT'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: '$(Build.ArtifactStagingDirectory)/WindowsVirtualMachine.json'
    csmParametersFile: '$(Build.ArtifactStagingDirectory)/WindowsVirtualMachine.parameters.json'
    overrideParameters: |
      -administratorLogin $(vmsUser) 
      -administratorLoginPassword $(vmsAdminPass)
    deploymentMode: 'Incremental'